yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from posts.views import page_not_found, server_error

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    path("404/", page_not_found),
    path("500/", server_error),
    path('auth/', include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
    path("about/", include("about.urls", namespace="about")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

yatube/templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе |</a>
        <a href="{% url 'about:tech' %}">Технологии</a>
    </p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">
        <b>Ya</b></span>tube © {{ year }}, все права защищены.</p>
</footer>

yatube/templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'index' %}"><span style="color:red"><b>Ya</b></span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">


        {% if user.is_authenticated %}
        <a class="p-2 text-dark" href="{% url 'post_create' %}">Новая запись</a>
        Пользователь: {{ user.username }}.


        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}

        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}

    </nav>
</nav>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/includes/short_pictures.html
<div class="card mb-3 mt-1 shadow-sm">
          {% load thumbnail %}
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img" src="{{ im.url }}">
          {% endthumbnail %}
        </div>

yatube/templates/includes/short_post.html
<!-- Начало блока с отдельным постом -->
<div class="card mb-3 mt-1 shadow-sm">
    <div class="card-body">
        <p class="card-text">
            {# Обязательно для всех ссылок используем {% url %} #}
            {# Тут делаем ссылку из name урла и передаем необходимый параметр в данном случае username #}
            <a href="{% url 'profile' username=author.username %}"><strong class="d-block text-gray-dark">@{{ author.username }}</strong></a>
            {# Не забываем про linebreaksbr #}
            {{ post.text|linebreaksbr }}
        </p>
        {% include "includes/short_pictures.html" %}
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group ">
                 <a class="btn btn-sm text-muted" href="{% url 'post' post_id=post.id %}" role="button">Добавить комментарий</a>
                {# Объекты пользователей нужно сравнивать напрямую #}
                {% if post.author == request.user %}
                <a class="btn btn-sm text-muted" href="{% url 'post_edit' post_id=post.id %}" role="button">Редактировать</a>
                {% endif %}

            </div>

            <small class="text-muted">{{ post.pub_date|date:"d M Y"}}</small>

        </div>
    </div>
</div>

yatube/templates/includes/short_profile.html
<div class="card">
    <div class="card-body">
        <div class="h2">
            {{ author.get_full_name }}
        </div>
        <div class="h3 text-muted">
            @{{ author.username }}
        </div>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="h6 text-muted">
                Подписчиков: XXX <br />
                Подписан: XXX
            </div>
        </li>
        <li class="list-group-item">
            <div class="h6 text-muted">
                Записей: {{ author.posts.count }}
            </div>
        </li>
    </ul>
</div>